version: '3.8'

services:
  # MongoDB for development
  mongodb:
    image: mongo:7.0
    container_name: dnd-tracker-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dnd_tracker_dev
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - dnd-tracker-network

  # Redis for session storage and caching
  redis:
    image: redis:7.2-alpine
    container_name: dnd-tracker-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redispassword
    volumes:
      - redis_data:/data
    networks:
      - dnd-tracker-network

  # Development database management UI
  mongo-express:
    image: mongo-express:1.0
    container_name: dnd-tracker-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - dnd-tracker-network

  # Redis management UI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: dnd-tracker-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379:0:redispassword
    depends_on:
      - redis
    networks:
      - dnd-tracker-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  dnd-tracker-network:
    driver: bridge