/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EncountersRoute } from './routes/encounters'
import { Route as CharactersRoute } from './routes/characters'
import { Route as IndexRoute } from './routes/index'

// Create/Update Routes

const EncountersRouteWithChildren = EncountersRoute._addFileChildren()
const CharactersRouteWithChildren = CharactersRoute._addFileChildren()
const IndexRouteWithChildren = IndexRoute._addFileChildren()

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/encounters': {
      id: '/encounters'
      path: '/encounters'
      fullPath: '/encounters'
      preLoaderRoute: typeof EncountersRouteWithChildren
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteWithChildren,
  CharactersRouteWithChildren,
  EncountersRouteWithChildren,
})

/* prettier-ignore-end */