/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterRoute } from './routes/register'
import { Route as LoginRoute } from './routes/login'
import { Route as DashboardRoute } from './routes/dashboard'
import { Route as IndexRoute } from './routes/index'

// Create/Update Routes

const RegisterRouteObj = RegisterRoute
const LoginRouteObj = LoginRoute
const DashboardRouteObj = DashboardRoute
const IndexRouteObj = IndexRoute

// Create and export the route tree

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexRouteObj
    parentRoute: typeof rootRoute
  }
  '/dashboard': {
    id: '/dashboard'
    path: '/dashboard'
    fullPath: '/dashboard'
    preLoaderRoute: typeof DashboardRouteObj
    parentRoute: typeof rootRoute
  }
  '/login': {
    id: '/login'
    path: '/login'
    fullPath: '/login'
    preLoaderRoute: typeof LoginRouteObj
    parentRoute: typeof rootRoute
  }
  '/register': {
    id: '/register'
    path: '/register'
    fullPath: '/register'
    preLoaderRoute: typeof RegisterRouteObj
    parentRoute: typeof rootRoute
  }
}

export interface FileRoutesById {
  __root__: {
    id: '__root__'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof rootRoute
  }
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexRouteObj
    parentRoute: typeof rootRoute
  }
  '/dashboard': {
    id: '/dashboard'
    path: '/dashboard'
    fullPath: '/dashboard'
    preLoaderRoute: typeof DashboardRouteObj
    parentRoute: typeof rootRoute
  }
  '/login': {
    id: '/login'
    path: '/login'
    fullPath: '/login'
    preLoaderRoute: typeof LoginRouteObj
    parentRoute: typeof rootRoute
  }
  '/register': {
    id: '/register'
    path: '/register'
    fullPath: '/register'
    preLoaderRoute: typeof RegisterRouteObj
    parentRoute: typeof rootRoute
  }
}

export const fileRoutesByPath: FileRoutesByPath = {
  '/': IndexRouteObj,
  '/dashboard': DashboardRouteObj,
  '/login': LoginRouteObj,
  '/register': RegisterRouteObj,
}

export const fileRoutesById: FileRoutesById = {
  __root__: rootRoute,
  '/': IndexRouteObj,
  '/dashboard': DashboardRouteObj,
  '/login': LoginRouteObj,
  '/register': RegisterRouteObj,
}

export const routeTree = rootRoute.addChildren({
  IndexRouteObj,
  DashboardRouteObj,
  LoginRouteObj,
  RegisterRouteObj,
})

/* prettier-ignore-end */